name: Scheduled Cron Job

on:
  schedule:
    - cron: "0 0 * * *" # 매일 한국 시간 오전 9시에 실행 (UTC 기준으로 오전 0시)

jobs:
  call-vercel-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call Vercel API
        run: |
          curl -X POST https://us-central1-dev-alarm.cloudfunctions.net/sendEmailNotification
